//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnBinhFarm.WEBUSC {
    
    
    public partial class GroupProductAndArticle {
        
        /// <summary>
        /// LGroup1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnBinhFarm.WEBUSC.LGroup LGroup1;
        
        /// <summary>
        /// GroupProduct1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnBinhFarm.WEBUSC.GroupProduct GroupProduct1;
    }
}
