//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSHOP {
    
    
    public partial class ctsp {
        
        /// <summary>
        /// SanphamBanChay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HPSHOP.WEBUSC.SanphamBanChay SanphamBanChay1;
        
        /// <summary>
        /// NDSP1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HPSHOP.WEBUSC.NDSP NDSP1;
    }
}
