//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnBinhFarm {
    
    
    public partial class Tintuc {
        
        /// <summary>
        /// HotArticle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnBinhFarm.WEBUSC.HotArticle HotArticle1;
        
        /// <summary>
        /// ArticleByGroup1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnBinhFarm.WEBUSC.ArticleByGroup ArticleByGroup1;
        
        /// <summary>
        /// SanphamBanChay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AnBinhFarm.WEBUSC.SanphamBanChay SanphamBanChay1;
    }
}
